### ISSUE TITLE
org.json classes conflict with the current json library

### ISSUE THREAD

**Issue by Typraeurion** [SAP/gigya-java-sdk#8]
I’ve just encountered an error after deploying some code that wasn’t seen on my development box:
`java.lang.NoSuchMethodError: org.json.JSONObject.isEmpty()Z`
After a bunch of digging around I found that the `gigya-java-sdk-3.2.4.jar` bundles its own version of org.json.JSONObject which conflicts with the one provided by `json-20200518.jar` (https://mvnrepository.com/artifact/org.json/json/20200518).  The Gigya SDK should not be bundling its own copies of these classes; it should have a dependency on the official JSON library.

**Comment by sammadaan30** [comment]
Facing same issue, but unable to identify which jar its conflicting with

**Comment by benoh-sap** [comment]
This issue was resolved on version 3.3.1

**Comment by benoh-sap** [comment]
This issue was resolved on version 3.3.1
